### ISSUE TITLE
Minor inaccuracy - UAC Security Boundary

### ISSUE THREAD

**Issue by a4004** [xaitax/TotalRecall#2]
Hey @xaitax 

Love your work, really awesome repo showcasing serious flaws in this new Recal "feature". When will MSFT ever learn? 😂 

Just want to point something out to you though, you mentioned UAC is not a security boundary which is factually incorrect. The article you quoted from @Microsoft does mention that "**Same-desktop Elevation** is not a security boundary", however that refers to an insecure configuration of UAC whereby the allow/deny prompt is presented on the user's desktop rather than the secure desktop (where the screen dims). This configuration is not the default on Windows and must be manually configured for UAC to no longer function as a reliable security boundary.

> More important, Same-desktop Elevation in UAC isn't a security boundary. It can be hijacked by unprivileged software that runs on the same desktop. Same-desktop Elevation should be considered a convenience feature. (https://learn.microsoft.com/en-us/troubleshoot/windows-server/windows-security/disable-user-account-control)

I'm not necessarily saying that UAC is perfect, as there are ways to bypass it with varying degrees of success but I think it's important to get the context right when dealing with security issues that have great potential impact.

**Comment by a4004** [comment]
That sure is interesting that two different Microsoft docs contradict each other. I'd think if they are using the secure desktop by default - then, regardless whether it's vulnerable or not, it would be at least considered a security boundary of some kind. But no, I guess then it seems MSFT knowingly ship a UAC system that isn't even achieving its intended purpose by default. That is kind of funny, and scary at the same time.

**Comment by namazso** [comment]
It does achieve its intended purpose - which was bullying more programs into working without admin, so that enterprise administrators can actually take away admin from their users without crippling the workflow.
